[package]
name = "AsyncE_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.16"
ic-cdk-timers = "0.10"

uuid = { version = "1.10.0", features = ["v4", "js"] }
serde = { version = "1.0", features = ["derive"] }
