name: DFX Workflow

on:
  push:
    branches:
      - main

jobs:
  dfx-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dfx sstup toolkit
        uses: dfinity/setup-dfx@main

      - name: Update cargo to prevent errors when compiling
        run: cargo update

      - name: Add wasm
        run: rustup target add wasm32-unknown-unknown

      - name: Install npm packages
        run: npm i

      - name: Start dfx server in the background
        run: dfx start --background

      - name: Deploy canisters using dfx
        run: dfx deploy
