name: DFX Workflow

on:
  push:
    branches:
      - main

jobs:
  dfx-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dfx
        uses: dfinity/setup-dfx@main

      - name: Confirm successful installation
        run: dfx --version

      - name: Update cargo so no error
        run: cargo update

      - name: Add wasm
        run: rustup target add wasm32-unknown-unknown

      - name: Install NPM packages
        run: npm i

      - name: Start dfx server in the background
        run: dfx start --background

      - name: Deploy canisters
        run: dfx deploy

      - name: Build docker image
        run: docker build . --file docker/Dockerfile --tag asynce:$(date +%s)
